### ISSUE TITLE
Animation 

### ISSUE THREAD

**Issue by this-kin** [martinoyovo/flutter-banking-app#2]
Hello there SIRS I would love to contribute to this awesome project by adding animations to it, this is my first contribution......I hope to get a reply from you soon Thanks 🙏

**Comment by martinoyovo** [comment]
That will be good

**Comment by this-kin** [comment]
If you don't mind adding me as a contributor so I can do ma thingy sir

**Comment by martinoyovo** [comment]
Just make a first pull request and I will review it.
